title: Afonso Eduardo
email:
description: Afonso Eduardo - Personal Page
github_username: oznof
repository: oznof/oznof.github.io
url: "https://oznof.github.io"
minimal_mistakes_skin: dark
search: false

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-sitemap

author:
  name             : "Afonso Eduardo"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "PhD student in Machine Learning<br>University of Edinburgh<br>School of Informatics, ANC"
  location         : #
  email            : "aflm.eduardo@gmail.com"
  github           : "oznof"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

atom_feed:
  hide: true